ProxyPreserveHost On
ProxyRequests Off

RequestHeader set X-Forwarded-Proto "https"

RedirectMatch 302 ^/sRNAmeta$ /sRNAmeta/

ProxyPass        /sRNAmeta/websocket/        ws://127.0.0.1:10804/websocket/
ProxyPassReverse /sRNAmeta/websocket/        ws://127.0.0.1:10804/websocket/

ProxyPass        /sRNAmeta/autoreload/       ws://127.0.0.1:10804/autoreload/
ProxyPassReverse /sRNAmeta/autoreload/       ws://127.0.0.1:10804/autoreload/

ProxyPass        /sRNAmeta/session/          http://127.0.0.1:10804/session/
ProxyPassReverse /sRNAmeta/session/          http://127.0.0.1:10804/session/

ProxyPass        /sRNAmeta/react/app_shell/  http://127.0.0.1:10804/react/app_shell/
ProxyPassReverse /sRNAmeta/react/app_shell/  http://127.0.0.1:10804/react/app_shell/

ProxyPass        /sRNAmeta/css/              http://127.0.0.1:10804/css/
ProxyPassReverse /sRNAmeta/css/              http://127.0.0.1:10804/css/

ProxyPass        /sRNAmeta/app-static/       http://127.0.0.1:10804/app-static/
ProxyPassReverse /sRNAmeta/app-static/       http://127.0.0.1:10804/app-static/

ProxyPass        /sRNAmeta/                  http://127.0.0.1:10804/
ProxyPassReverse /sRNAmeta/                  http://127.0.0.1:10804/
