worker_processes auto;

events {
  worker_connections 4096;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 4096;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }

  upstream srnameta_shiny_upstream {
    ip_hash;
    server srnameta_app_1:3838;
    server srnameta_app_2:3838;
    server srnameta_app_3:3838;
  }

  server {
    listen 8080;
    server_name _;

    client_max_body_size 1g;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_connect_timeout 60s;

    location / {
      proxy_pass http://srnameta_shiny_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_buffering off;
      proxy_request_buffering off;
    }
  }
}
